"use client";
export default function TermsConditions() {
  
  return (

    
    <div className="customContainer">
            <div className="policies">
                <div className="header">
                    <h2>FullOnTravel - Terms & Conditions</h2>
                </div>
                <div className="document">
                    <h4>Applicability of The Agreement</h4>
                    <p>This agreement ("user agreement") incorporates the terms and conditions for Full On Travel Pvt. Ltd. (FOTPL) and its brand Fullon Travel to provide services to the person (s) ("the User") intending to purchase or inquiring for any products and/ or services of FOTPL by using FOTPL"s websites or using any other customer interface channels of FOTPL which includes its sales persons, offices, call centres, advertisements, information campaigns etc. Both User and FOTPL are individually referred to as 'parties' to the agreement and collectively referred to as 'parties'.</p>
                    <h4>User's Responsibility of Cognizance</h4>
                    <p>The Users availing services from FOTPL shall be deemed to have read, understood and expressly accepted the terms and conditions of this agreement, which shall govern the desired transaction or provision of such services by FOTPL for all purposes, and shall be binding on the User. All rights and liabilities of the User and/or FOTPL with respect to any services to be provided by FOTPL shall be restricted to the scope of this agreement.
                        <br />FOTPL reserves the right, in its sole discretion, to terminate the access to any or all FOTPL websites or its other sales channels and the related services or any portion thereof at any time, without notice, for general maintenance or any reason whatsoever.</p>
                    <p>In addition to this Agreement, there are certain terms of service (TOS) specific to the services rendered/ products provided by FOTPL like the air tickets, holiday packages etc. Such TOS will be provided/ updated by FOTPL which shall be deemed to be a part of this Agreement and in the event of a conflict between such TOS and this Agreement, the terms of this Agreement shall prevail. The User shall be required to read and accept the relevant TOS for the service/ product availed by the User. Additionally, the Service Provider itself may provide terms and guidelines that govern particular features, offers or the operating rules and policies applicable to each Service (for example, flights, hotel reservations, packages, etc.). The User shall be responsible for ensuring compliance with the terms and guidelines or operating rules and policies of the Service Provider with whom the User elects to deal, including terms and conditions set forth in a Service Provider's fare rules, contract of carriage or other rules.
                        <br />FOTPL's Services are offered to the User conditioned on acceptance without modification of all the terms, conditions and notices contained in this Agreement and the TOS, as may be applicable from time to time. For the removal of doubts, it is clarified that availing of the Services by the User constitutes an acknowledgement and acceptance by the User of this Agreement and the TOS. If the User does not agree with any part of such terms, conditions and notices, the User must not avail FOTPL's Services.
                        <br />In the event that any of the terms, conditions, and notices contained herein conflict with the Additional Terms or other terms and guidelines contained within any other FOTPL document, then these terms shall control.</p>
                    <h4>Third Party Account Information</h4>
                    <p>By using the Account Access service in FOTPL's websites, the User authorizes FOTPL and its agents to access third party sites, including that of Banks and other payment gateways, designated by them or on their behalf for retrieving requested information. While registering, the User will choose a password and is responsible for maintaining the confidentiality of the password and the account.</p>
                    <p>The User is fully responsible for all activities that occur while using their password or account. It is the duty of the User to notify FOTPL immediately in writing of any unauthorised use of their password or account or any other breach of security. FOTPL will not be liable for any loss that may be incurred by the User as a result of unauthorised use of his password or account, either with or without his knowledge. The User shall not use anyone else's password at any time.</p>
                    <h4>Confidentiality</h4>
                    <p>Any information which is specifically mentioned by FOTPL as Confidential shall be maintained confidentially by the user and shall not be disclosed unless as required by law or to serve the purpose of this agreement and the obligations of both the parties therein.</p>
                    <h4>Website And Mobile App Usage</h4>
                    <p>Your use of any information or materials on the website and mobile app is entirely at your own risk, for which FOTPL shall not undertake any liability. It shall be your own accountability to ensure that any products, services or information available through our website or app, meet your explicit specifications.</p>
                    <p>You are restrained from altering, duplicating, distributing, transmitting, reproducing, publishing, licensing or selling any information, software, products or services acquired from this website or app. Duplication of content from the website and app is forbidden which is in accordance with the copyright notice and forms a part of the Terms of Use. Additionally, FOTPL reserves private rights to modify, revise, and delete any of the contents without giving prior notice to any person.</p>
                    <h4>Onus Of The User</h4>
                    <p>FOTPL is responsible only for the transactions that are done by the User through FOTPL. FOTPL will not be responsible for screening, censoring or otherwise controlling transactions, including whether the transaction is legal and valid as per the laws of the land of the User.
                        <br />The accuracy of the data and bookings have to be cross verified by the user. The user warrants that they will abide by all such additional procedures and guidelines, as modified from time to time, in connection with the use of the services. The User further warrants that they will comply with all applicable laws and regulations regarding use of the services with respect to the jurisdiction concerned for each transaction.</p>
                    <h4>Insurance</h4>
                    <p>Unless explicitly provided by FOTPL in any specific service or deliverable, obtaining sufficient insurance coverage is the obligation/option of the user and FOTPL doesn't accept any claims arising out of such scenarios.</p>
                    <p>Insurance, if any provided as a part of the service/ product by FOTPL shall be as per the terms and conditions of the insuring company. The User shall contact the insurance company directly for any claims or disputes and FOTPL shall not provide any express or implied undertakings for acceptance of the claims by the insurance company.</p>
                    <h4>Force Majure Circumstances</h4>
                    <p>The user agrees that there can be exceptional circumstances where the service operators like the airlines, hotels, the respective transportation providers or concerns may be unable to honor the confirmed bookings due to various reasons like climatic conditions, labor unrest, insolvency, business exigencies, government decisions, operational and technical issues, route and flight cancellations etc. If FOTPL is informed in advance of such situations where dishonor of bookings may happen, it will make its best efforts to provide a similar alternative to its customers or refund the booking amount after reasonable service charges, if supported and refunded by that respective service operator. The user agrees that FOTPL being an agent for facilitating the booking services shall not be responsible for any such circumstances and the customers have to contact that service provider directly for any further resolutions and refunds.
                        <br />The User agrees that in situations due to any technical or other failure in FOTPL, services committed earlier may not be provided or may involve substantial modification. In such cases, FOTPL shall refund the entire amount received from the customer for availing such services minus the applicable cancellation, refund or other charges, which shall completely discharge any and all liabilities of FOTPL against such non-provision of services or deficiencies. Additional liabilities, if any, shall be borne by the User.</p>
                    <p>FOTPL shall not be liable for delays or inabilities in performance or nonperformance in whole or in part of its obligations due to any causes that are not due to its acts or omissions and are beyond its reasonable control, such as acts of God, fire, strikes, embargo, acts of government, acts of terrorism or other similar causes, problems at airlines, rails, buses, hotels or transporters end. In such an event, the user affected will be promptly given notice as the situation permits.</p>
                    <p>Without prejudice to whatever is stated above, the maximum liability on part of FOTPL arising under any circumstances, in respect of any services offered on the site, shall be limited to the refund of total amount received from the customer for availing the services less any cancellation, refund or others charges, as may be applicable. In no case the liability shall include any loss, damage or additional expense whatsoever beyond the amount charged by FOTPL for its services.</p>
                    <p>In no event shall FOTPL and/or its suppliers be liable for any direct, indirect, punitive, incidental, special, consequential damages or any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the FOTPL website(s) or any other channel . Neither shall FOTPL be responsible for the delay or inability to use the FOTPL websites or related services, the provision of or failure to provide services, or for any information, software, products, services and related graphics obtained through the FOTPL website(s), or otherwise arising out of the use of the FOTPL website(s), whether based on contract, tort, negligence, strict liability or otherwise. FOTPL is not responsible for any errors, omissions or representations on any of its pages or on any links or on any of the linked website pages.</p>
                    <h4>Safety Of Data Downloaded</h4>
                    <p>The User understands and agrees that any material and/or data downloaded or otherwise obtained through the use of the Service is done entirely at their own discretion and risk and they will be solely responsible for any damage to their computer systems or loss of data that results from the download of such material and/or data.</p>
                    <p>Nevertheless, FOTPL will always make its best endeavours to ensure that the content on its websites or other information channels are free of any virus or such other malwares.</p>
                    <h4>Feedback From Customer And Solicitation</h4>
                    <p>The User is aware that FOTPL provides various services like hotel bookings, car rentals, holidays and would like to learn about them, to enhance his / her travel experience. The User hereby specifically authorises FOTPL to contact the User with offers on various services offered by it through direct mailers, e-mailers, telephone calls, short messaging services (SMS) or any other medium, from time to time. In case that the customer chooses not to be contacted, he /she shall write to FOTPL for specific exclusion at support@fullontravel.com or provide his / her preferences to the respective service provider. The customers are advised to read and understand the privacy policy of FOTPL on its website in accordance with which FOTPL contacts, solicits the user or shares the user's information.</p>
                    <h4>Proprietary Rights</h4>
                    <p>FOTPL may provide the User with contents such as sound, photographs, graphics, video or other material contained in sponsor advertisements or information. This material may be protected by copyrights, trademarks, or other intellectual property rights and laws.
                        <br />The User may use this material only as expressly authorised by FOTPL and shall not copy, transmit or create derivative works of such material without express authorization.</p>
                    <p>The User acknowledges and agrees that he/she shall not upload, post, reproduce, or distribute any content on or through the Services that is protected by copyright or other proprietary right of a third party, without obtaining the written permission of the owner of such right.</p>
                    <p>Any copyrighted or other proprietary content distributed with the consent of the owner must contain the appropriate copyright or other proprietary rights notice. The unauthorised submission or distribution of copyrighted or other proprietary content is illegal and could subject the User to personal liability or criminal prosecution.</p>
                    <h4>Visa Obligations of the User</h4>
                    <p>The travel bookings done by FOTPL are subject to the applicable requirements of Visa which are to be obtained by the individual traveller. FOTPL is not responsible for any issues, including inability to travel, arising out of such Visa requirements and is also not liable to refund for the untraveled bookings due to any such reason.</p>
                    <h4>Indemnification</h4>
                    <p>The User agrees to indemnify, defend and hold harmless FOTPL and/or its affiliates, their websites and their respective lawful successors and assigns from and against any and all losses, liabilities, claims, damages, costs and expenses (including reasonable legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by FOTPL and/or its affiliates, partner websites and their respective lawful successors and assigns that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by the User pursuant to this agreement.</p>
                    <p>The user shall be solely and exclusively liable for any breach of any country specific rules and regulations or general code of conduct and FOTPL cannot be held responsible for the same.</p>
                    <h4>Right To Refuse</h4>
                    <p>FOTPL at its sole discretion reserves the right to not to accept any customer order without assigning any reason thereof. Any contract to provide any service by FOTPL is not complete until full money towards the service is received from the customer and accepted by FOTPL.
                        <br />Without prejudice to the other remedies available to FOTPL under this agreement, the TOS or under applicable law, FOTPL may limit the user's activity, or end the user's listing, warn other users of the user's actions, immediately temporarily/indefinitely suspend or terminate the user's registration, and/or refuse to provide the user with access to the website if:
                        <br />The user is in breach of this agreement, the TOS and/or the documents it incorporates by reference.</p>
                    <p>FOTPL is unable to verify or authenticate any information provided by the user; or FOTPL believes that the user's actions may infringe on any third party rights or breach any applicable law or otherwise result in any liability for the user, other users of the website and/or FOTPL.</p>
                    <p>FOTPL may at any time in its sole discretion reinstate suspended users. Once the user have been indefinitely suspended the user shall not register or attempt to register with FOTPL or use the website in any manner whatsoever until such time that the user is reinstated by FOTPL.</p>
                    <p>Notwithstanding the foregoing, if the user breaches this agreement, the TOS or the documents it incorporates by reference, FOTPL reserves the right to recover any amounts due and owing by the user to FOTPL and/or the service provider and to take strict legal action as FOTPL deems necessary.</p>
                    <h4>Right To Cancellation In Case Of Invalid User Information</h4>
                    <p>The User expressly undertakes to provide to FOTPL only correct and valid information while requesting for any services under this agreement, and not to make any misrepresentation of facts at all. Any default on part of the User would vitiate this agreement and shall disentitle the User from availing the services from FOTPL.</p>
                    <p>In case FOTPL discovers or has reasons to believe at any time during or after receiving a request for services from the User that the request for services is either unauthorised or the information provided by the User or any of them is not correct or that any fact has been misrepresented by him, FOTPL in its sole discretion shall have the unrestricted right to take any steps against the User(s), including cancellation of the bookings, etc. without any prior intimation to the User. In such an event, FOTPL shall not be responsible or liable for any loss or damage that may be caused to the User or any of them as a consequence of such cancellation of booking or services.</p>
                    <p>The User unequivocally indemnifies FOTPL of any such claim or liability and shall not hold FOTPL responsible for any loss or damage arising out of measures taken by FOTPL for safeguarding its own interest and that of its genuine customers. This would also include FOTPL denying/cancelling any bookings on account of suspected fraud transactions.</p>
                    <h4>Severability</h4>
                    <p>If any provision of this agreement is determined to be invalid or unenforceable in whole or in part, such invalidity or unenforceability shall attach only to such provision or part of such provision and the remaining part of such provision and all other provisions of this Agreement shall continue to be in full force and effect.</p>
                    <h4>Headings</h4>
                    <p>The headings and subheadings herein are included for convenience and identification only and are not intended to describe, interpret, define or limit the scope, extent or intent of this agreement, terms and conditions, notices, or the right to use this website by the User contained herein or any other section or pages of FOTPL Websites or its partner websites or any provision hereof in any manner whatsoever.</p>
                    <p>In the event that any of the terms, conditions, and notices contained herein conflict with the Additional Terms or other terms and guidelines contained within any particular FOTPL website, then these terms shall control.</p>
                    <h4>Relationship</h4>
                    <p>None of the provisions of any agreement, terms and conditions, notices, or the right to use this website by the User contained herein or any other section or pages of FOTPL Websites or its partner websites, shall be deemed to constitute a partnership between the User and FOTPL and no party shall have any authority to bind or shall be deemed to be the agent of the other in any way.</p>
                    <h4>Updation Of The Information By FOTPL</h4>
                    <p>User acknowledges that FOTPL provides services with reasonable diligence and care. It endeavours its best to ensure that User does not face any inconvenience. However, at some times, the information, software, products, and services included in or available through the FOTPL websites or other sales channels and ad materials may include inaccuracies or typographical errors which will be immediately corrected as soon as FOTPL notices them. Changes are/may be periodically made/added to the information provided such. FOTPL may make improvements and/or changes in the FOTPL websites at any time without any notice to the User. Any advice received except through an authorised representative of FOTPL via the FOTPL websites should not be relied upon for any decisions.</p>
                    <h4>Modification Of These Terms Of Use</h4>
                    <p>FOTPL reserves the right to change the terms, conditions, and notices under which the FOTPL websites are offered, including but not limited to the charges. The User is responsible for regularly reviewing these terms and conditions.</p>
                    <h4>Jurisdiction</h4>
                    <p>FOTPL hereby expressly disclaims any implied warranties imputed by the laws of any jurisdiction or country other than those where it is operating its offices. FOTPL considers itself and intends to be subject to the jurisdiction only of the courts of Gurugram, India.</p>
                    <h4>Responsibilities Of User Vis-a-Vis The Agreement</h4>
                    <p>The User expressly agrees that use of the services is at their sole risk. To the extent FOTPL acts only as a booking agent on behalf of third party service providers, it shall not have any liability whatsoever for any aspect of the standards of services provided by the service providers. In no circumstances shall FOTPL be liable for the services provided by the service provider. The services are provided on an "as is" and "as available" basis. FOTPL may change the features or functionality of the services at any time, in their sole discretion, without notice. FOTPL expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement. No advice or information, whether oral or written, which the User obtains from FOTPL or through the services shall create any warranty not expressly made herein or in the terms and conditions of the services. If the User does not agree with any of the terms above, they are advised not to read the material on any of the FOTPL pages or otherwise use any of the contents, pages, information or any other material provided by FOTPL. The sole and exclusive remedy of the User in case of disagreement, in whole or in part, of the user agreement, is to discontinue using the services after notifying FOTPL in writing.</p>
                    <h4>Usage Of Customer's Holiday Pictures</h4>
                    <p>Any picture or video shared by the customers during or post the trip in the support groups or emails, will be used in the social media platform to engage the audience. However, if you are not comfortable with the same, kindly drop a mail to help@fullontravel.com and your request will immediately be looked into.</p>
                </div>
            </div>
        </div>
  );
}
